SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600 

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 16
PLAYER_X_SPAWN = SCREEN_WIDTH // 2
PLAYER_Y_SPAWN = SCREEN_HEIGHT // 2
PLAYER_TURN_RATE = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 5
SHOT_SPEED = 400